# Creating reading and writing

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

Setup complete.

## 生产dataframe格式表格

In [2]:
fruits = pd.DataFrame([[30,21]],columns=['Apples','Bananas'])
fruits

   Apples  Bananas
0      30       21

In [3]:
fruits_sales = pd.DataFrame([[35,21],[23,56]],
                            columns=['Apples','Bananas'],
                           index = ['2017 sales','2018 slaes'])
fruits_sales

            Apples  Bananas
2017 sales      35       21
2018 slaes      23       56

## 生产series格式表格

In [4]:
quantitiones=['4 cups','5 cups','1 large','1 can']
items = ['Flour','Milk','Eggs','spam']
ingredients = pd.Series(quantitiones,index = items,name = 'Dinner')
ingredients

Flour     4 cups
Milk      5 cups
Eggs     1 large
spam       1 can
Name: Dinner, dtype: object

## 读取csv格式文件

In [5]:
review1 = pd.read_csv("D:/jupyter_notebook/dataset/titanic/test.csv" ,index_col=0)

### .head()表明读取前五行并且显示出来

In [6]:
review1.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
animals = pd.DataFrame({'cows':[12.20],'goats':[30,29]},index=['2000','2001'])
animals

      cows  goats
2000  12.2     30
2001  12.2     29

### 将animals保存为csv数据集

In [8]:
animals.to_csv("D:/jupyter_notebook/dataset/pandas/animals.csv")

In [9]:
reviews2 = pd.read_csv("D:/jupyter_notebook/dataset/pandas/winemag-data-130k-v2.csv",index_col=0)

- 注意，如果不加index_col表示的含义会有部分不同

In [10]:
reviews2.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Indexing, Selecting & Assigning

In [11]:
reviews2.country

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [12]:
reviews2['country']

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [13]:
reviews2['country'][0]

'Italy'

In [14]:
reviews2.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

In [15]:
reviews2.iloc[:,0] #先行后列

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

## 不加 0 表示是所有，现阶段代码表示取第一列

In [16]:
reviews2.iloc[:3,0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

### 表示前三行的第一列

In [17]:
reviews2.iloc[1:3,0]

1    Portugal
2          US
Name: country, dtype: object

In [18]:
reviews2.iloc[[0,1,2],0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [19]:
reviews2.iloc[-5:,0]

129966    Germany
129967         US
129968     France
129969     France
129970     France
Name: country, dtype: object

## 基于标签的选择

In [20]:
reviews2.loc[0,'country']

'Italy'

- 注意，如果这里使用iloc将会报错。

In [21]:
reviews2.loc[:,['taster_name','taster_twitter_handle','points']]

          taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
...               ...                   ...     ...
129969     Roger Voss            @vossroger      90
129970     Roger Voss            @vossroger      90

[129971 rows x 3 columns]

- 值得注意的是，iloc[0:3]不包含3，是0，1，2.但loc[0:3]恰恰相反，表示0，1，2，3

In [22]:
reviews2.set_index('title')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

## 条件选择

In [23]:
reviews2.country == 'Italy'

0          True
1         False
          ...
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [24]:
reviews2.loc[reviews2.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

## 如何表示 and or 等符号呢？

### & 表示并集

In [25]:
reviews2.loc[(reviews2.country == 'Italy') & (reviews2.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

### | 表示 or

In [26]:
reviews2.loc[(reviews2.country == 'Italy') | (reviews2.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## pandas 会带一些内置的条件选择器

### isin（） 允许选择（）内的一些值

In [27]:
reviews2.loc[reviews2.country.isin(['Italy','Frace'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

### isnull（）（notnull()）允许显示不是或者空的值

In [28]:
reviews2.loc[reviews2.price.notnull()]#过滤掉缺少价格标签的

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [29]:
reviews2['critic'] = 'everyone'

In [30]:
reviews2

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone

In [31]:
reviews2['index_backwards'] = range(len(reviews2),0,-1)

In [32]:
reviews2

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [33]:
desc = reviews2.description

In [34]:
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
                                ...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [35]:
first_description = reviews2.description.loc[0]
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [36]:
first_row = reviews2.loc[0]
first_row

country                                                        Italy
description        Aromas include tropical fruit, broom, brimston...
                                         ...
critic                                                      everyone
index_backwards                                               129971
Name: 0, Length: 15, dtype: object

In [37]:
first_descriptions = reviews2.description.loc[0:9]
first_descriptions

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
                           ...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, Length: 10, dtype: object

In [38]:
sample_reviews2 = reviews2.loc[[1,2,3,5,8]]
sample_reviews2

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,everyone,129966
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel,everyone,129963

In [39]:
lie = ['country','province','region_1','region_2']
han = [0,1,10,100]
df = reviews2.loc[han,lie]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

In [40]:
df = reviews2.loc[:99,['country','variety']]
df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
..       ...                       ...
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

In [41]:
italin_wines = reviews2.loc[reviews2.country == 'Italy']
italin_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo,everyone,129965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS,everyone,10
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano,everyone,9

In [42]:
top_oceania_wines = reviews2.loc[(reviews2.country.isin(['Italy','New Zealand'])) & (reviews2.points >= 95)]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
350,Italy,"After a few minutes in the glass, this stunnin...",Vignolo Riserva,97,150.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Cavallotto 2010 Vignolo Riserva (Barolo),Nebbiolo,Cavallotto,everyone,129621
361,Italy,"Enticing scents of ripe berry, underbrush, gri...",Simposio,95,60.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Bel Colle 2012 Simposio (Barolo),Nebbiolo,Bel Colle,everyone,129610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125847,Italy,Costa Russi presents a dark wall of ripe fruit...,Costa Russi,95,495.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2009 Costa Russi Nebbiolo (Langhe),Nebbiolo,Gaja,everyone,4124
126240,Italy,Ben Ryé is always a fabulous dessert wine from...,Ben Ryé,95,40.0,Sicily & Sardinia,Passito di Pantelleria,NaN,NaN,NaN,Donnafugata 2008 Ben Ryé (Passito di Pantelle...,Zibibbo,Donnafugata,everyone,3731

In [43]:
top_oceania_wines = reviews2[(reviews2.country.isin(['Italy','New Zealand'])) & (reviews2.points >= 95)]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
350,Italy,"After a few minutes in the glass, this stunnin...",Vignolo Riserva,97,150.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Cavallotto 2010 Vignolo Riserva (Barolo),Nebbiolo,Cavallotto,everyone,129621
361,Italy,"Enticing scents of ripe berry, underbrush, gri...",Simposio,95,60.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Bel Colle 2012 Simposio (Barolo),Nebbiolo,Bel Colle,everyone,129610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125847,Italy,Costa Russi presents a dark wall of ripe fruit...,Costa Russi,95,495.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2009 Costa Russi Nebbiolo (Langhe),Nebbiolo,Gaja,everyone,4124
126240,Italy,Ben Ryé is always a fabulous dessert wine from...,Ben Ryé,95,40.0,Sicily & Sardinia,Passito di Pantelleria,NaN,NaN,NaN,Donnafugata 2008 Ben Ryé (Passito di Pantelle...,Zibibbo,Donnafugata,everyone,3731

- 删除一列axis=1，删除一行axis=0

In [44]:
reviews2.drop(['critic','index_backwards'],axis = 1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

# Summary Functions and Maps

## 描述性统计

### describe()

In [45]:
reviews2.points.describe()

count    129971.000000
mean         88.447138
             ...
75%          91.000000
max         100.000000
Name: points, Length: 8, dtype: float64

In [46]:
reviews2.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

### mean()

In [47]:
reviews2.points.mean()

88.44713820775404

### unique()

In [48]:
reviews2.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

### value_counts()统计该数据之不同值得个数

In [49]:
reviews2.taster_name.value_counts()

Roger Voss           25514
Michael Schachner    15134
                     ...
Fiona Adams             27
Christina Pickard        6
Name: taster_name, Length: 19, dtype: int64

- 映射，将现有数据创建为新的表示数据，转为自己想要的格式。map()是返回新的，apply()是转换后的series.但不会改变原有数据结构

In [50]:
reviews2_points_mean = reviews2.points.mean()
reviews2.points.map(lambda p: p-reviews2_points_mean)

0        -1.447138
1        -1.447138
            ...
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [51]:
def remean_points(row):
    row.points = row.points - reviews2_points_mean
    return row
reviews2.apply(remean_points,axis = 'columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [52]:
reviews2.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967

## 练习

In [53]:
median_points = reviews2.points.median()
median_points

88.0

In [54]:
counties = reviews2.country.unique()
counties

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

- 若要查看唯一值的列表以及它们在 Series 中出现的频率，请使用 value_counts 方法。

In [55]:
reviews2_per_country = reviews2.country.value_counts()
reviews2_per_country

US          54504
France      22093
            ...
Slovakia        1
China           1
Name: country, Length: 43, dtype: int64

In [56]:
centered_price = reviews2.points - reviews2.price.mean()
centered_price

0         51.636611
1         51.636611
            ...
129969    54.636611
129970    54.636611
Name: points, Length: 129971, dtype: float64

- 注意 idxmax() 的巧妙用法

In [57]:
bargain_idx = (reviews2.points / reviews2.price).idxmax()
bargain_wine = reviews2.loc[bargain_idx,'title']
bargain_wine

'Bandit NV Merlot (California)'

In [58]:
n_trop = reviews2.description.map(lambda desc:'tropical' in desc).sum()
n_fruity = reviews2.description.map(lambda desc:'fruity' in desc).sum()
description_counts1 = pd.Series([n_trop,n_fruity],index = ['tropical','fruity'])
description_counts1

tropical    3607
fruity      9090
dtype: int64

In [59]:
description_counts2 = pd.DataFrame([['tropical','fruity'],[n_trop,n_fruity]],
                               columns =['word','number'],
                               index = [1,2])
description_counts2

       word  number
1  tropical  fruity
2      3607    9090

In [60]:
def stars(row):
    if row.country =="Canada":
        return 3
    elif row.points >=95:
        return 3
    elif row.points>=85:
        return 2
    else:
        return 1
star_ratings = reviews2.apply(stars,axis='columns')

In [61]:
star_ratings

0         2
1         2
         ..
129969    2
129970    2
Length: 129971, dtype: int64

In [62]:
reviews2

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

# Grouping and Sorting

## groupby()

- groupby()创建一组评论，该评论为给定得wine分配了相同得分数值，然后抓取points()并计算出现次数，value_counts()只是groupby()得快捷方法

In [63]:
reviews2.groupby('points').points.count()

points
80     397
81     692
      ...
99      33
100     19
Name: points, Length: 21, dtype: int64

- 获取每个分值类别中最便宜的wine的价格

In [64]:
reviews2.groupby('points').price.min()

points
80      5.0
81      5.0
       ...
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

- 从数据集中的每个酒庄中选择第一款评论的葡萄酒名称的一种方法

In [65]:
reviews2.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

- 按国家和省份挑选组好的wine

In [66]:
reviews2.groupby(['country','province']).apply(lambda df:df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
...                               ...
Uruguay   San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                          designation  points  price  \
country   province
Argentina Mendoza Province           Nicasia Vineyard      97  120.0
          Other                               Reserva      95   90.0
...                                               ...     ...    ...
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0
          Uruguay           Blend 002 Limited Edition      91   22.0

                                    province region_1 region_2  \
country   province
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN
          Other                        Other    Salta      NaN
...                                      ...      ...      ...
Uruguay   San Jose                  San Jose      NaN      NaN
          Uruguay                    Uruguay      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
...                                       ...                   ...
Uruguay   San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
...                                                                       ...
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery  \
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
...                                           ...                   ...
Uruguay   San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

                              critic  index_backwards
country   province
Argentina Mendoza Province  everyone            47217
          Other             everyone            51668
...                              ...              ...
Uruguay   San Jose          everyone            90073
          Uruguay           everyone            90610

[425 rows x 15 columns]

### agg()方法

- 同时在dataframe上运行一堆不同的函数

In [67]:
reviews2.groupby(['country']).price.agg([len,min,max])

              len   min    max
country
Argentina  3800.0   4.0  230.0
Armenia       2.0  14.0   15.0
...           ...   ...    ...
Ukraine      14.0   6.0   13.0
Uruguay     109.0  10.0  130.0

[43 rows x 3 columns]

## multi-indexes

- 多索引与常规索引的不同之处在于它具有多个级别

In [68]:
countries_reviewed = reviews2.groupby(['country','province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [69]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

- 最常使用的多索引方法是转换回常规索引的方法， 即 reset_index（） 方法

In [70]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
..         ...               ...   ...
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

## 排序

- sort_values() 默认为升序排序，想要其降序时，利用ascending = False

In [71]:
countries_reviewed.sort_values(by = 'len')

                                 len
country province
Greece  Muscat of Kefallonian      1
        Sterea Ellada              1
...                              ...
US      Washington              8639
        California             36247

[425 rows x 1 columns]

In [72]:
countries_reviewed.sort_values(by = 'len',ascending = False)

                      len
country province
US      California  36247
        Washington   8639
...                   ...
Chile   Coelemu         1
Greece  Beotia          1

[425 rows x 1 columns]

- 要按索引值排序 sort_index（）

In [73]:
countries_reviewed.sort_index()

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [74]:
countries_reviewed.sort_values(by = ['country','len'])

                             len
country   province
Argentina Other              536
          Mendoza Province  3264
...                          ...
Uruguay   Uruguay             24
          Canelones           43

[425 rows x 1 columns]

In [75]:
countries_reviewed.sort_values(by = ['country','len'],ascending = False)

                             len
country   province
Uruguay   Canelones           43
          Uruguay             24
...                          ...
Argentina Mendoza Province  3264
          Other              536

[425 rows x 1 columns]

## 练习

In [76]:
reviews2_written = reviews2.groupby(['taster_twitter_handle']).taster_twitter_handle.count()
reviews2_written

taster_twitter_handle
@AnneInVino        3685
@JoeCz             5147
                   ...
@winewchristina       6
@worldwineguys     1005
Name: taster_twitter_handle, Length: 15, dtype: int64

In [77]:
best_rating_per_price = reviews2.groupby('price')['points'].max().sort_index()
best_rating_per_price

price
4.0       86
5.0       87
          ..
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [78]:
best_rating_per_price = reviews2.groupby('price').points.max().sort_index()
best_rating_per_price

price
4.0       86
5.0       87
          ..
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

这里借助 groupby('price') 方法，按照 price（价格）这一属性对数据进行分组。其作用是把数据集中价格相同的记录归为一组。分组完成后，针对每个分组中的 points（评分）列运用  max()函数，这样就能得到每个价格组对应的最高评分。最后使用sort_index()方法，按照价格（也就是索引）对结果进行升序排列，从而让数据按照价格从低到高的顺序呈现。**同时注意上述两行代码的区别**

In [79]:
price_extremes =reviews2.groupby(['variety']).price.agg([min,max])
price_extremes

              min   max
variety
Abouriou     15.0  75.0
Agiorgitiko  10.0  66.0
...           ...   ...
Çalkarası    19.0  19.0
Žilavka      15.0  15.0

[707 rows x 2 columns]

In [80]:
sorted_varieties = price_extremes.sort_values(by=['min','max'],ascending = False)
sorted_varieties

             min    max
variety
Ramisco    495.0  495.0
Terrantez  236.0  236.0
...          ...    ...
Vital        NaN    NaN
Zelen        NaN    NaN

[707 rows x 2 columns]

In [81]:
reviewer_mean_ratings = reviews2.groupby(['taster_name']).points.mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
                        ...
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, Length: 19, dtype: float64

In [82]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
           ...
75%      88.975256
max      90.562551
Name: points, Length: 8, dtype: float64

In [83]:
country_variety_counts = reviews2.groupby(['country','variety']).size().sort_values(ascending=False)
country_variety_counts

country    variety
US         Pinot Noir            9885
           Cabernet Sauvignon    7315
                                 ...
Italy      Moscato di Noto          1
Argentina  Barbera                  1
Length: 1612, dtype: int64

- size()函数，这样就能得到**每个分组中的记录数量**，也就是每个国家每种葡萄品种的出现次数。

# Data Types and Missing Values

## Dtype

In [84]:
reviews2.price.dtype

dtype('float64')

In [85]:
reviews2.dtypes

country            object
description        object
                    ...
critic             object
index_backwards     int32
Length: 15, dtype: object

## astype() 数据类型的转换

In [86]:
reviews2.points.astype('float64')

0         87.0
1         87.0
          ...
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [87]:
reviews2.index.dtype

dtype('int64')

- Pandas还支持其他数据类型，如分类数据和时间序列数据。

## 缺失数据

### 缺失数据的查询

- 缺失的值被赋予NaN，并且由于技术原因这些值始终是float64类型。
- 选择 NaN 条目，可以使用 pd.isnull（）或其配套的 pd.notnull（）

In [88]:
reviews2[pd.isnull(reviews2.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines,everyone,129058
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier,everyone,126840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ,everyone,381
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot,everyone,71

### 缺失数据的替换

- fillna（）提供了一些不同的策略来减少这些数据

In [89]:
reviews2.region_2.fillna('Nuknown')

0         Nuknown
1         Nuknown
           ...
129969    Nuknown
129970    Nuknown
Name: region_2, Length: 129971, dtype: object

- 想要一个替换非空值使用*reolace()*

In [90]:
reviews2.taster_twitter_handle.replace('@kerinokeefe','@kerino') # 从 @kerinokeefe 更改为 @kerino

0            @kerino
1         @vossroger
             ...
129969    @vossroger
129970    @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

## 练习

最常见的葡萄酒产区有哪些？创建一个 Series，计算每个值在 region_1 字段中出现的次数。该字段通常缺少数据，因此将缺少的值替换为未知 。按降序排序。

In [91]:
reviews2.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)

Unknown                               21247
Napa Valley                            4480
                                      ...
Sonoma County-Santa Barbara County        1
Cabernet de Saumur                        1
Name: region_1, Length: 1230, dtype: int64

# Renaming and Combining

## 重命名

- rename() 更改索引名或者列名

In [95]:
reviews2.rename(columns={'points':'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

- rename() 允许通过分别指定*index*或者*column*关键字参数来重命名，支持多种输入格式，但字典是最方便的。

In [97]:
reviews2.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

- 行/列索引都有自己的*name*属性，rename_axis() 可用于更改这些名称。通俗来讲改变行或者列的名称

In [100]:
reviews2.rename_axis('wines',axis ='rows').rename_axis('fields',axis = 'columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
wines,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [104]:
reviews2.set_index('country')

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
country,,,,,,,,,,,,,,
Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [106]:
reviews2.set_index('price')

,country,description,designation,points,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
price,,,,,,,,,,,,,,
NaN,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
15.0,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32.0,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
21.0,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

## 组合

### concat()

- 给定一个元素列表，此函数将沿轴将这些元素混合在一起。
- 假设a,b为两个表格，pd.concat([a,b])可将其合并

### join()

- 允许组合具有共同索引的不同DataFrame对象。如下：

 left = canadian_youtube.set_index(['title', 'trending_date'])
 right = british_youtube.set_index(['title', 'trending_date'])
 left.join(right, lsuffix='_CAN', rsuffix='_UK')

lsuffix 和 rsuffix 参数在此处是必需的，因为数据在英国和加拿大数据集中具有相同的列名。如果这不是真的（因为，比如说，我们事先重命名了它们），我们就不需要它们。